version: "3.9"
services:
  api:
    build: ./services/api-fastapi
    ports: ["8080:8080"]
    environment:
      - REPO_ROOT=/app
      - CATALOG_DIR=/app/preskills/catalog
    volumes:
      - ./:/app
  ui:
    working_dir: /app/ui/transcript-explorer
    image: node:18-alpine
    command: sh -lc "npm i && npm run dev -- --host 0.0.0.0"
    ports: ["5173:5173"]
    volumes:
      - ./:/app
    environment:
      - VITE_API_BASE=http://localhost:8080
